services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        environment:
            APP_ENV: production
            APP_DEBUG: true
            APP_KEY: base64:9zyvZg0GRySpXVIejdnAu3gj25vI1p281qE2+mvzcF0=
            APP_URL: http://localhost
            DB_CONNECTION: pgsql
            DB_HOST: db
            DB_PORT: 5432
            DB_DATABASE: covid-tracker
            DB_USERNAME: postgres
            DB_PASSWORD: elonmask
        volumes:
            - .:/var/www/html
        networks:
            - laravel_network
        ports:
            - "9000:9000"

    db:
        image: postgres:13
        container_name: postgres_db
        restart: unless-stopped
        environment:
            POSTGRES_DB: covid-tracker
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: elonmask
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - laravel_network

    webserver:
        image: nginx:alpine
        container_name: nginx_server
        restart: unless-stopped
        ports:
            - "80:80"  # Use port 80 to access the app on http://localhost
        volumes:
            - .:/var/www/html  # Corrected: Mount the entire project, not just the public folder
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel_network

networks:
    laravel_network:

volumes:
    db_data:
